package com.shiro.elysiae.model.enums;

public enum AuditAction {
    PATIENT_CREATED, PATIENT_UPDATED,
    DOCTOR_CREATED,
    APPOINTMENT_BOOKED, APPOINTMENT_CANCELLED,
    INVOICE_GENERATED, PAYMENT_RECEIVED,
    LAB_REQUEST_CREATED, LAB_RESULT_ENTERED,
    MEDICINE_DISPENSED,
    USER_LOGIN, USER_LOGOUT, USER_CREATED, USER_DELETED, USER_UPDATED,
    PATIENT_CREDENTIAL_RESET, PATIENT_DELETED, APPOINTMENT_UPDATED, STAFF_CREDENTIAL_RESET, DOCTOR_CREDENTIAL_RESET, DOCTOR_UPDATED, DOCTOR_SCHEDULE_UPDATED, PATIENT_TRANSFERRED, PATIENT_DISCHARGED, PATIENT_ADMITTED, MEDICAL_RECORD_CREATED, DOCTOR_DELETED, WARD_DELETED, BED_DELETED, PRESCRIPTION_ADDED, MEDICAL_RECORD_UPDATED,VITALS_LOGGED
    ,LAB_REQUEST_UPDATED,MEDICINE_ADDED,MEDICINE_UPDATED,MEDICINE_STOCK_UPDATED,INVOICE_ITEM_ADDED, SERVICE_RATE_UPDATED

}
